### PR TITLE
Refactor of code

### PR DESCRIPTION
**Pull request by salam99823**
# Changes:

## Added:
- feature `parallel` for fast work on large data.
- pedantic lint params.
- private utils module.

## Moved:
- `collider::rapier2d` and `collider::avian2d` to root of crate.
- logic of public functions to utils for simply.

## Removed:
- [`thiserror`](https://crates.io/crates/thiserror) from dependencies.
- `collider` module.

## Other
- dependency on `bevy` replaced with `bevy_math`.

### CODE REVIEW

**Comment by salam99823** [comment]
Hi, what do you think about the latest commit to [dev branch](https://github.com/salam99823/bevy_collider_gen/tree/dev).

**Comment by shnewto** [comment]
Hello @salam99823! There's a lot of really useful refactors here and _thank you_ for updating the rapier2d example to use linear velocity instead of just moving the sprite to new pixels 🙃 

Regarding the changes in your PR here (your `main` branch). I'm on totally board, they're good changes. My initial implementation had in mind a kind of "drop a new physics framework into the `collider` directory" and be up and running, but it only adds noise, it's just as easy to drop a new framework into the `src` directory.

Regarding the changes in your `dev` branch, those are good changes too but they took me a minute to think about. Looking at your code, it's clear that using `generate_multi_collider` and `generate_collider` instead of individual symbols for every collider makes the code cleaner and more light weight. Initially I liked the experience of being able to write `generate_` and tab complete in the editor the collider you were looking for. But again, it's not harder to use `ColliderType`, it actually makes it much clearer to the user what colliders are supported. 

All that said, both branches are changes I'll be very glad to incorporate into this project. Thank you for all the time you've given to this and the `edges` project. 

I'll hold off on merging in case you're thinking you'll update your main branch with your dev changes.

**Comment by shnewto** [comment]
@salam99823 is this ready for review?

**Comment by salam99823** [comment]
Hello @shnewto! Yes, I think it can be released as a new version.

**Comment by shnewto** [comment]
@salam99823 thank you again for these substantial and very positive refactors!

**Comment by salam99823** [comment]
I'm glad you liked it.

**Comment by salam99823** [comment]
I'm glad you liked it.

**Pull request merged**
