### PR TITLE
Update to Bevy 0.14. Switch from bevy_xpbd_2d to avian2d

### PR DESCRIPTION
**Pull request by tnajdek**
Both examples start, and the colliders are nicely generated. The scale in `rapier2d_colliders` feels off. I'm not sure if that's a new issue or if it was already present in the previous version.

### CODE REVIEW

**Comment by shnewto** [comment]
awesome, thanks for this! I'll take a look at the avian stuff a bit later today. if nothing else, I can make a note in #13 that the colliders could use some attention

**Comment by tnajdek** [comment]
fixed formatting

**Comment by shnewto** [comment]
🤔 yeah something's up with the colliders after the switch
mfaster

**Comment by shnewto** [comment]
But @tnajdek that doesn't have to be your problem 😄 thanks for this update! I'll try and figure out what's up with the avian colliders this week, but if you feel like poking at it I'd be happy for the help!

**Pull request merged**
